# Generated by Django 4.2 on 2024-02-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_text_banner_text_information_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendpost',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
